@FinancialMcp.Api_HostAddress = http://localhost:5058

GET {{FinancialMcp.Api_HostAddress}}/api/categories
Accept: application/json

###

GET {{FinancialMcp.Api_HostAddress}}/api/counterparties
Accept: application/json

###

GET {{FinancialMcp.Api_HostAddress}}/api/metrics/summary?year=2026&month=6
Accept: application/json

###
